version: "3.8"
services:
  web:
    image: dt-app
    build: ../build
    ports:
      - "4040:80"
    networks:
      - dt-network

  redis:
    image: redis
    volumes:
      - dt-data:/data
    command: redis-server --appendonly yes
    networks:
      - dt-network

volumes:
  dt-data:

networks:
  dt-network:
