version: "3.8"
services:

  web:
    image: dt-app
    build: ../build
    ports:
      - "8080:80"
    networks:
      - dt-network

  redis:
    image: redis
    volumes:
      - dt-data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - dt-network

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - dt-network


volumes:
  dt-data:
  portainer:

networks:
  agent-network:
    driver: overlay
    attachable: true
  dt-network:
